default:
  seed: 42

hyper_param:
  lr: 0.002
  epochs: 5

  weight_decay: 1.e-5

  logging_steps: 10
  warmup_steps: 10
  gradient_steps: 8

  batch_size: 128

  loss: "focal"
  optim: "adamw"
  workers: 0
  output_dir: "outputs/train"
  hub_name: "upar2026-track1-model"

  # Augmentation
  aug: True
  median: True
  horizontal_flip: True
  random_resized_crop: False
  affine: True
  safe_rotate: False
  coarse_dropout: True
  gaussian_blur: False
  color_jitter: False
  rgb_shift: False
  image_compression: False

  # Resize
  height: 256
  width: 256

data:
  data_path: "data/annotations/train.csv"
  data_name: null
  num_samples: 10

losses:
  focal:
    alpha: 0.25
    gamma: 0.2

  weighted_bce:
    weight:
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1

optim:
  adamw:
    beta: [0.9, 0.999]

  sgd:
    momentum: 0.9